#!/bin/bash -x
#==================================================#
# SETUP GEOSERVER
#==================================================#

echo 'Setting up geoserver'

#Check if geoserver is already on here, if not then download it
if [ -a "geoserver-2.2.4-war.zip" ]
then
    echo 'geoserver-2.2.4.zip found, skipping download'
else
    echo 'Downloading geoserver'
    wget http://downloads.sourceforge.net/project/geoserver/GeoServer/2.2.4/geoserver-2.2.4-war.zip
fi

#stop tomcat, so we can make some adjustments
service tomcat7 stop

#put geoserver into tomcat
unzip -o geoserver-2.2.4-war.zip 
unzip -o geoserver.war -d geoserver 
sudo mv geoserver /var/lib/tomcat7/webapps/

# sed replace the username and password in datastore-config.xml
sed -i "s/the_username/$U_NAME/g" geoserver-config/catami/catamidb/datastore.xml
sed -i "s/the_password/$PASSWORD/g" geoserver-config/catami/catamidb/datastore.xml

# relace the host with given host
sed -i "s/the_host/$SERVER/g" geoserver-config/catami/catamidb/datastore.xml

#copy the config over to geoserver, and make tomcat the owner
sudo cp -r geoserver-config/catami /var/lib/tomcat7/webapps/geoserver/data/workspaces/
chown -R tomcat7 /var/lib/tomcat7/webapps
chgrp -R tomcat7 /var/lib/tomcat7/webapps

#change username and password for admin
# look in /var/lib/tomcat7/webapps/geoserver/data/security
sed -i "s/admin=geoserver/$U_NAME=$PASSWORD/g" /var/lib/tomcat7/webapps/geoserver/data/security/users.properties

echo 'Restarting tomcat'
sudo service tomcat7 restart

echo 'Restarting apache'
sudo service apache2 restart
