#!/bin/bash -x
#==================================================#
# SETUP DOLLY
#==================================================#

echo 'Setting up dolly'

sudo apt-get -y install maven2
sudo apt-get -y install default-jdk

git clone https://github.com/catami/dolly.git

cd dolly

mvn clean:clean
mvn compile war:war
sudo cp target/dolly.war /var/lib/tomcat7/webapps
